function [true_max_profit, true_optimal_x] = Optimal_capacitated ()
    global I J L;
%     global utility_v0 revenue_matrix_r utility_matrix_v interation_para_phi;
%     global lower_case_C upper_case_C ;

    %%%%%%% Optimal
    Optimal_t_Start = tic;
    global true_max_profit;
    global true_optimal_x;

    true_max_profit = -Inf;
    true_optimal_x = zeros(I,J);

    recursion_to_find_the_optimal_capacitated (1,zeros(I,J));

    Optimal_t_End = toc(Optimal_t_Start);
    fprintf('\n');
    fprintf('Running time of the enumeration method: %d minutes and %f seconds\n', floor(Optimal_t_End/60), rem(Optimal_t_End,60));
end

function recursion_to_find_the_optimal_capacitated(group_index, temp_x)
    global I J L;
%     global utility_v0 revenue_matrix_r utility_matrix_v interation_para_phi;
    global lower_case_C upper_case_C ;

    if group_index == (J +1) 
        if (sum(sum(temp_x))) > upper_case_C
            return;
        end
        policy_x = zeros(I,J);
        get_policy_x_from_temp_x(temp_x,policy_x,1);
        return;
    end

    for i = 0 : min(I,lower_case_C)
        temp_x(1 : i, group_index) = 1;
        temp_x(i+1:end, group_index) = 0;
        recursion_to_find_the_optimal_capacitated (group_index+1, temp_x);
    end
end


function [] = get_policy_x_from_temp_x (temp_x, policy_x, j)
    global I J L;
%     global utility_v0 revenue_matrix_r utility_matrix_v interation_para_phi;
%     global lower_case_C upper_case_C ;    
    global order_matrix;
    global true_max_profit;
    global true_optimal_x;

    if j == J+1
%         revenue = 0;
        revenue = calculate_revenue (policy_x);
        if revenue >= true_max_profit
                true_max_profit = revenue;
                true_optimal_x = policy_x;
        end
        return;
    end

    for order_index = 1 : size(order_matrix{j},2)
        policy_x(:,j) = 0;
        if sum(temp_x(:,j)) == 0
            get_policy_x_from_temp_x(temp_x, policy_x, j+1);
        else
            if order_matrix{j}(sum(temp_x(:,j)),order_index) == -1 
                return;
            end
            policy_x(order_matrix{j}(1:sum(temp_x(:,j)),order_index),j) = 1;
            get_policy_x_from_temp_x(temp_x, policy_x, j+1);
        end
    end
end


function [revenue] = calculate_revenue (current_x)
    global I J L num_group_in_one_cluster utility_v0 revenue_matrix_r utility_matrix_v interation_para_phi;
    vx_matrix = utility_matrix_v .* current_x;
    vx_matrix(end+1,:) = ones(1,J);
    
    revenue = 0;
    Lambda_of_cluster_vector = zeros(1,( J - (num_group_in_one_cluster - 1)*L));
    gamma_of_cluster_vector = zeros(1,( J - (num_group_in_one_cluster - 1)*L));
    
    for index_L = 1 : L
        j = num_group_in_one_cluster * (index_L - 1) + 1;
        j_end = num_group_in_one_cluster * index_L;
        current_x_for_cluster = current_x(:,j:j_end);
        
        if num_group_in_one_cluster == 2
            gamma_of_cluster_vector(index_L) = 1 + current_x_for_cluster(:,1)'*utility_matrix_v(:,j) + current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1) ...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1));
            Lambda_of_cluster_vector(index_L) = (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))...
                *(1 + interation_para_phi(j,j+1)*(current_x_for_cluster(:,2)' * utility_matrix_v(:,j+1))) ...
                + (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1))) ...
                *(1 + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)' * utility_matrix_v(:,j)));
        elseif num_group_in_one_cluster == 3
            gamma_of_cluster_vector(index_L) = 1 + current_x_for_cluster(:,1)'*utility_matrix_v(:,j) + current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1) + current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2) ...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2));
            Lambda_of_cluster_vector(index_L) = (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j))) + (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))...
                                + (current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2))) + ...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j));
        elseif num_group_in_one_cluster == 4
            gamma_of_cluster_vector(index_L) = 1 + current_x_for_cluster(:,1)'*utility_matrix_v(:,j) + current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1) + current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2) + current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3)...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+3)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3));

                Lambda_of_cluster_vector(index_L) = (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j))) + (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))...
                                + (current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2))) + (current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...  
                                + interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))... 
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j)) ...
                                + interation_para_phi(j,j+3)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...  
                                + interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))... 
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)'* (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))... 
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1));


        end
    end
    
    for index_j = num_group_in_one_cluster * L + 1 : J
        gamma_of_cluster_vector(index_j - (num_group_in_one_cluster - 1)*L) = 1 + current_x(:,index_j)'*utility_matrix_v(:,index_j);
        Lambda_of_cluster_vector(index_j - (num_group_in_one_cluster - 1)*L) = current_x(:,index_j)'* (revenue_matrix_r(:,index_j).* utility_matrix_v(:,index_j));
    end

    Gamma = prod(gamma_of_cluster_vector);

    for cluster_index = 1 : (L + J - num_group_in_one_cluster * L)
        revenue = revenue + Lambda_of_cluster_vector(cluster_index)/(gamma_of_cluster_vector(cluster_index)*((utility_v0-1)/Gamma + 1));
    end

end