function [best_PR_revenue, best_PR_X] = Pure_RO_capacitated ()
    global I J;
    global utility_v0 revenue_matrix_r utility_matrix_v;
    global upper_case_C;
    
    PR_t_Start = tic;
    best_PR_revenue_direct = -inf;
    best_PR_X = zeros(I,J);
    
    order_matrix_pure_RO = StaticMNL_pure_order_revenue(I, J, revenue_matrix_r, utility_matrix_v);
    
    for subpolicy_index = 1 : size(order_matrix_pure_RO,2)
        for i = 0 : min(I*J,upper_case_C)
            temp_x = zeros(I,J);
            label = true;
            for ordering_index = 1 : i
                if order_matrix_pure_RO(ordering_index,subpolicy_index) == -1
                    label = false;
                    break;
                end
                temp_x(order_matrix_pure_RO(ordering_index,subpolicy_index)) = 1;
            end
            if label == false
                continue;
            end
            temp_denominator = utility_v0 + sum(sum(utility_matrix_v.*temp_x));
            temp_numerator = sum(sum(revenue_matrix_r.*utility_matrix_v.*temp_x));
            temp_revenue = temp_numerator/temp_denominator;
            if temp_revenue > best_PR_revenue_direct
                best_PR_revenue_direct = temp_revenue;
                best_PR_X = temp_x;
            end
        end
    end
    
    best_PR_revenue = calculate_revenue (best_PR_X);
    
    PR_t_End = toc(PR_t_Start);
    fprintf('Running time of the pure revenue: %d minutes and %f seconds\n', floor(PR_t_End/60), rem(PR_t_End,60));
end

function [order_matrix] = StaticMNL_pure_order_revenue(I, J, revenue_matrix_r, utility_matrix_v)
%     [glo_sort_v, glo_sort_v_index] = sort(revenue_matrix_r(:)','descend');
%     [glo_sort_r, glo_sort_r_index] = sort(revenue_matrix_r(:)','descend');

    temp_v = utility_matrix_v(:);
    temp_r = revenue_matrix_r(:);
    temp_v(I*J+1) = 0;
    temp_r(I*J+1) = 0;
    
    interaction_point = [];
    interaction_line_num = [];
    for i1 = 1 : I*J
        for i2 = i1+1 : I*J+1
            cross_value = (temp_v(i1) * temp_r(i1) - temp_v(i2) * temp_r(i2)) / (temp_v(i1) - temp_v(i2));
            interaction_point(end+1) = cross_value;
            interaction_line_num(1,end+1) = i1;
            interaction_line_num(2,end) = i2;
        end
    end
    
    [interaction_point, index] = sort(interaction_point);
    interaction_line_num = interaction_line_num(:,index);
    
    [~,ordering_of_I] = sort(temp_v, 'descend');
    [~,index_of_v] = sort(ordering_of_I);
    
    order_matrix = zeros(I*J+1,(size(interaction_point,2)-1));
    ordering_of_I(end) = -1;
    order_matrix(:,1) = ordering_of_I;
    for index = 1 : size(interaction_point,2)-1
        i1 = interaction_line_num(1,index);
        i2 = interaction_line_num(2,index);
        ordering_of_I(index_of_v(i1)) = i2;
        ordering_of_I(index_of_v(i2)) = i1;
        tmp = index_of_v(i1);
        index_of_v(i1) = index_of_v(i2);
        index_of_v(i2) = tmp;
        
        for below_0 = index_of_v(I*J+1) : I*J+1
            ordering_of_I(below_0) = -1;
        end
        
        order_matrix(:,index) = ordering_of_I;
    end
end


function [revenue] = calculate_revenue (current_x)
    global I J L num_group_in_one_cluster utility_v0 revenue_matrix_r utility_matrix_v interation_para_phi;
    vx_matrix = utility_matrix_v .* current_x;
    vx_matrix(end+1,:) = ones(1,J);
    
    revenue = 0;
    Lambda_of_cluster_vector = zeros(1,( J - (num_group_in_one_cluster - 1)*L));
    gamma_of_cluster_vector = zeros(1,( J - (num_group_in_one_cluster - 1)*L));
    
    for index_L = 1 : L
        j = num_group_in_one_cluster * (index_L - 1) + 1;
        j_end = num_group_in_one_cluster * index_L;
        current_x_for_cluster = current_x(:,j:j_end);
        
        if num_group_in_one_cluster == 2
            gamma_of_cluster_vector(index_L) = 1 + current_x_for_cluster(:,1)'*utility_matrix_v(:,j) + current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1) ...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1));
            Lambda_of_cluster_vector(index_L) = (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))...
                *(1 + interation_para_phi(j,j+1)*(current_x_for_cluster(:,2)' * utility_matrix_v(:,j+1))) ...
                + (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1))) ...
                *(1 + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)' * utility_matrix_v(:,j)));
        elseif num_group_in_one_cluster == 3
            gamma_of_cluster_vector(index_L) = 1 + current_x_for_cluster(:,1)'*utility_matrix_v(:,j) + current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1) + current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2) ...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2));
            Lambda_of_cluster_vector(index_L) = (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j))) + (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))...
                                + (current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2))) + ...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j));
        elseif num_group_in_one_cluster == 4
            gamma_of_cluster_vector(index_L) = 1 + current_x_for_cluster(:,1)'*utility_matrix_v(:,j) + current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1) + current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2) + current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3)...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+3)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3));

                Lambda_of_cluster_vector(index_L) = (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j))) + (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))...
                                + (current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2))) + (current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...  
                                + interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))... 
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j+1,j+2)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j)) ...
                                + interation_para_phi(j,j+3)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))...  
                                + interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))... 
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)'* (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+2,j+3)*(current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))... 
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,1)' * (revenue_matrix_r(:,j).* utility_matrix_v(:,j)))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,2)' * (revenue_matrix_r(:,j+1).* utility_matrix_v(:,j+1)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,3)' * (revenue_matrix_r(:,j+2).* utility_matrix_v(:,j+2)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1))*(current_x_for_cluster(:,4)'*utility_matrix_v(:,j+3))...
                                + interation_para_phi(j,j+1)*interation_para_phi(j,j+2)*interation_para_phi(j,j+3)*interation_para_phi(j+1,j+2)*interation_para_phi(j+1,j+3)*interation_para_phi(j+2,j+3)...
                                * (current_x_for_cluster(:,4)' * (revenue_matrix_r(:,j+3).* utility_matrix_v(:,j+3)))*(current_x_for_cluster(:,1)'*utility_matrix_v(:,j))*(current_x_for_cluster(:,3)'*utility_matrix_v(:,j+2))*(current_x_for_cluster(:,2)'*utility_matrix_v(:,j+1));


        end
    end
    
    for index_j = num_group_in_one_cluster * L + 1 : J
        gamma_of_cluster_vector(index_j - (num_group_in_one_cluster - 1)*L) = 1 + current_x(:,index_j)'*utility_matrix_v(:,index_j);
        Lambda_of_cluster_vector(index_j - (num_group_in_one_cluster - 1)*L) = current_x(:,index_j)'* (revenue_matrix_r(:,index_j).* utility_matrix_v(:,index_j));
    end

    Gamma = prod(gamma_of_cluster_vector);

    for cluster_index = 1 : (L + J - num_group_in_one_cluster * L)
        revenue = revenue + Lambda_of_cluster_vector(cluster_index)/(gamma_of_cluster_vector(cluster_index)*((utility_v0-1)/Gamma + 1));
    end

end